# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import compute_pb2 as compute__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputeServiceStub(object):
    """Compute Service - For direct backend computation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/cyxwiz.protocol.ComputeService/Execute',
                request_serializer=compute__pb2.ComputeRequest.SerializeToString,
                response_deserializer=compute__pb2.ComputeResponse.FromString,
                _registered_method=True)
        self.ExecuteGraph = channel.unary_unary(
                '/cyxwiz.protocol.ComputeService/ExecuteGraph',
                request_serializer=compute__pb2.ExecuteGraphRequest.SerializeToString,
                response_deserializer=compute__pb2.ExecuteGraphResponse.FromString,
                _registered_method=True)
        self.StreamExecute = channel.stream_stream(
                '/cyxwiz.protocol.ComputeService/StreamExecute',
                request_serializer=compute__pb2.ComputeRequest.SerializeToString,
                response_deserializer=compute__pb2.ComputeResponse.FromString,
                _registered_method=True)


class ComputeServiceServicer(object):
    """Compute Service - For direct backend computation
    """

    def Execute(self, request, context):
        """Execute a single operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteGraph(self, request, context):
        """Execute multiple operations (graph)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExecute(self, request_iterator, context):
        """Stream operations for large workloads
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=compute__pb2.ComputeRequest.FromString,
                    response_serializer=compute__pb2.ComputeResponse.SerializeToString,
            ),
            'ExecuteGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteGraph,
                    request_deserializer=compute__pb2.ExecuteGraphRequest.FromString,
                    response_serializer=compute__pb2.ExecuteGraphResponse.SerializeToString,
            ),
            'StreamExecute': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamExecute,
                    request_deserializer=compute__pb2.ComputeRequest.FromString,
                    response_serializer=compute__pb2.ComputeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyxwiz.protocol.ComputeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyxwiz.protocol.ComputeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputeService(object):
    """Compute Service - For direct backend computation
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.ComputeService/Execute',
            compute__pb2.ComputeRequest.SerializeToString,
            compute__pb2.ComputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.ComputeService/ExecuteGraph',
            compute__pb2.ExecuteGraphRequest.SerializeToString,
            compute__pb2.ExecuteGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExecute(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cyxwiz.protocol.ComputeService/StreamExecute',
            compute__pb2.ComputeRequest.SerializeToString,
            compute__pb2.ComputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
