# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import deployment_pb2 as deployment__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in deployment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeploymentServiceStub(object):
    """============================================================================
    SERVICES
    ============================================================================

    Deployment Service - Manage model deployments
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDeployment = channel.unary_unary(
                '/cyxwiz.protocol.DeploymentService/CreateDeployment',
                request_serializer=deployment__pb2.CreateDeploymentRequest.SerializeToString,
                response_deserializer=deployment__pb2.CreateDeploymentResponse.FromString,
                _registered_method=True)
        self.GetDeployment = channel.unary_unary(
                '/cyxwiz.protocol.DeploymentService/GetDeployment',
                request_serializer=deployment__pb2.GetDeploymentRequest.SerializeToString,
                response_deserializer=deployment__pb2.GetDeploymentResponse.FromString,
                _registered_method=True)
        self.ListDeployments = channel.unary_unary(
                '/cyxwiz.protocol.DeploymentService/ListDeployments',
                request_serializer=deployment__pb2.ListDeploymentsRequest.SerializeToString,
                response_deserializer=deployment__pb2.ListDeploymentsResponse.FromString,
                _registered_method=True)
        self.StopDeployment = channel.unary_unary(
                '/cyxwiz.protocol.DeploymentService/StopDeployment',
                request_serializer=deployment__pb2.StopDeploymentRequest.SerializeToString,
                response_deserializer=deployment__pb2.StopDeploymentResponse.FromString,
                _registered_method=True)
        self.DeleteDeployment = channel.unary_unary(
                '/cyxwiz.protocol.DeploymentService/DeleteDeployment',
                request_serializer=deployment__pb2.DeleteDeploymentRequest.SerializeToString,
                response_deserializer=deployment__pb2.DeleteDeploymentResponse.FromString,
                _registered_method=True)
        self.GetDeploymentMetrics = channel.unary_unary(
                '/cyxwiz.protocol.DeploymentService/GetDeploymentMetrics',
                request_serializer=deployment__pb2.GetDeploymentMetricsRequest.SerializeToString,
                response_deserializer=deployment__pb2.GetDeploymentMetricsResponse.FromString,
                _registered_method=True)


class DeploymentServiceServicer(object):
    """============================================================================
    SERVICES
    ============================================================================

    Deployment Service - Manage model deployments
    """

    def CreateDeployment(self, request, context):
        """Create a new deployment (local or network)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeployment(self, request, context):
        """Get deployment status and details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeployments(self, request, context):
        """List user's deployments
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopDeployment(self, request, context):
        """Stop a running deployment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDeployment(self, request, context):
        """Delete a deployment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentMetrics(self, request, context):
        """Get deployment metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeploymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDeployment,
                    request_deserializer=deployment__pb2.CreateDeploymentRequest.FromString,
                    response_serializer=deployment__pb2.CreateDeploymentResponse.SerializeToString,
            ),
            'GetDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeployment,
                    request_deserializer=deployment__pb2.GetDeploymentRequest.FromString,
                    response_serializer=deployment__pb2.GetDeploymentResponse.SerializeToString,
            ),
            'ListDeployments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeployments,
                    request_deserializer=deployment__pb2.ListDeploymentsRequest.FromString,
                    response_serializer=deployment__pb2.ListDeploymentsResponse.SerializeToString,
            ),
            'StopDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.StopDeployment,
                    request_deserializer=deployment__pb2.StopDeploymentRequest.FromString,
                    response_serializer=deployment__pb2.StopDeploymentResponse.SerializeToString,
            ),
            'DeleteDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDeployment,
                    request_deserializer=deployment__pb2.DeleteDeploymentRequest.FromString,
                    response_serializer=deployment__pb2.DeleteDeploymentResponse.SerializeToString,
            ),
            'GetDeploymentMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentMetrics,
                    request_deserializer=deployment__pb2.GetDeploymentMetricsRequest.FromString,
                    response_serializer=deployment__pb2.GetDeploymentMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyxwiz.protocol.DeploymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyxwiz.protocol.DeploymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeploymentService(object):
    """============================================================================
    SERVICES
    ============================================================================

    Deployment Service - Manage model deployments
    """

    @staticmethod
    def CreateDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.DeploymentService/CreateDeployment',
            deployment__pb2.CreateDeploymentRequest.SerializeToString,
            deployment__pb2.CreateDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.DeploymentService/GetDeployment',
            deployment__pb2.GetDeploymentRequest.SerializeToString,
            deployment__pb2.GetDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeployments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.DeploymentService/ListDeployments',
            deployment__pb2.ListDeploymentsRequest.SerializeToString,
            deployment__pb2.ListDeploymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.DeploymentService/StopDeployment',
            deployment__pb2.StopDeploymentRequest.SerializeToString,
            deployment__pb2.StopDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.DeploymentService/DeleteDeployment',
            deployment__pb2.DeleteDeploymentRequest.SerializeToString,
            deployment__pb2.DeleteDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeploymentMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.DeploymentService/GetDeploymentMetrics',
            deployment__pb2.GetDeploymentMetricsRequest.SerializeToString,
            deployment__pb2.GetDeploymentMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TerminalServiceStub(object):
    """Terminal Service - Interactive terminal access to deployments
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/cyxwiz.protocol.TerminalService/CreateSession',
                request_serializer=deployment__pb2.CreateTerminalSessionRequest.SerializeToString,
                response_deserializer=deployment__pb2.CreateTerminalSessionResponse.FromString,
                _registered_method=True)
        self.StreamTerminal = channel.stream_stream(
                '/cyxwiz.protocol.TerminalService/StreamTerminal',
                request_serializer=deployment__pb2.TerminalData.SerializeToString,
                response_deserializer=deployment__pb2.TerminalData.FromString,
                _registered_method=True)
        self.ResizeTerminal = channel.unary_unary(
                '/cyxwiz.protocol.TerminalService/ResizeTerminal',
                request_serializer=deployment__pb2.TerminalResize.SerializeToString,
                response_deserializer=deployment__pb2.SimpleResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/cyxwiz.protocol.TerminalService/CloseSession',
                request_serializer=deployment__pb2.CloseTerminalSessionRequest.SerializeToString,
                response_deserializer=deployment__pb2.CloseTerminalSessionResponse.FromString,
                _registered_method=True)


class TerminalServiceServicer(object):
    """Terminal Service - Interactive terminal access to deployments
    """

    def CreateSession(self, request, context):
        """Create new terminal session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTerminal(self, request_iterator, context):
        """Bidirectional streaming for terminal data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizeTerminal(self, request, context):
        """Resize terminal window
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Close terminal session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TerminalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=deployment__pb2.CreateTerminalSessionRequest.FromString,
                    response_serializer=deployment__pb2.CreateTerminalSessionResponse.SerializeToString,
            ),
            'StreamTerminal': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTerminal,
                    request_deserializer=deployment__pb2.TerminalData.FromString,
                    response_serializer=deployment__pb2.TerminalData.SerializeToString,
            ),
            'ResizeTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.ResizeTerminal,
                    request_deserializer=deployment__pb2.TerminalResize.FromString,
                    response_serializer=deployment__pb2.SimpleResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=deployment__pb2.CloseTerminalSessionRequest.FromString,
                    response_serializer=deployment__pb2.CloseTerminalSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyxwiz.protocol.TerminalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyxwiz.protocol.TerminalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TerminalService(object):
    """Terminal Service - Interactive terminal access to deployments
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.TerminalService/CreateSession',
            deployment__pb2.CreateTerminalSessionRequest.SerializeToString,
            deployment__pb2.CreateTerminalSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTerminal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cyxwiz.protocol.TerminalService/StreamTerminal',
            deployment__pb2.TerminalData.SerializeToString,
            deployment__pb2.TerminalData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResizeTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.TerminalService/ResizeTerminal',
            deployment__pb2.TerminalResize.SerializeToString,
            deployment__pb2.SimpleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.TerminalService/CloseSession',
            deployment__pb2.CloseTerminalSessionRequest.SerializeToString,
            deployment__pb2.CloseTerminalSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelServiceStub(object):
    """Model Service - Upload/download models to/from CyxWiz Hub
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadMetadata = channel.unary_unary(
                '/cyxwiz.protocol.ModelService/UploadMetadata',
                request_serializer=deployment__pb2.UploadModelMetadataRequest.SerializeToString,
                response_deserializer=deployment__pb2.UploadModelMetadataResponse.FromString,
                _registered_method=True)
        self.UploadModel = channel.stream_unary(
                '/cyxwiz.protocol.ModelService/UploadModel',
                request_serializer=deployment__pb2.ModelChunk.SerializeToString,
                response_deserializer=deployment__pb2.SimpleResponse.FromString,
                _registered_method=True)
        self.DownloadMetadata = channel.unary_unary(
                '/cyxwiz.protocol.ModelService/DownloadMetadata',
                request_serializer=deployment__pb2.DownloadModelMetadataRequest.SerializeToString,
                response_deserializer=deployment__pb2.DownloadModelMetadataResponse.FromString,
                _registered_method=True)
        self.DownloadModel = channel.unary_stream(
                '/cyxwiz.protocol.ModelService/DownloadModel',
                request_serializer=deployment__pb2.DownloadModelMetadataRequest.SerializeToString,
                response_deserializer=deployment__pb2.ModelChunk.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/cyxwiz.protocol.ModelService/ListModels',
                request_serializer=deployment__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=deployment__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/cyxwiz.protocol.ModelService/DeleteModel',
                request_serializer=deployment__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=deployment__pb2.DeleteModelResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Model Service - Upload/download models to/from CyxWiz Hub
    """

    def UploadMetadata(self, request, context):
        """Upload model metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadModel(self, request_iterator, context):
        """Stream upload model file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadMetadata(self, request, context):
        """Download model metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModel(self, request, context):
        """Stream download model file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List models in marketplace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Delete model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadMetadata,
                    request_deserializer=deployment__pb2.UploadModelMetadataRequest.FromString,
                    response_serializer=deployment__pb2.UploadModelMetadataResponse.SerializeToString,
            ),
            'UploadModel': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadModel,
                    request_deserializer=deployment__pb2.ModelChunk.FromString,
                    response_serializer=deployment__pb2.SimpleResponse.SerializeToString,
            ),
            'DownloadMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadMetadata,
                    request_deserializer=deployment__pb2.DownloadModelMetadataRequest.FromString,
                    response_serializer=deployment__pb2.DownloadModelMetadataResponse.SerializeToString,
            ),
            'DownloadModel': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=deployment__pb2.DownloadModelMetadataRequest.FromString,
                    response_serializer=deployment__pb2.ModelChunk.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=deployment__pb2.ListModelsRequest.FromString,
                    response_serializer=deployment__pb2.ListModelsResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=deployment__pb2.DeleteModelRequest.FromString,
                    response_serializer=deployment__pb2.DeleteModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyxwiz.protocol.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyxwiz.protocol.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Model Service - Upload/download models to/from CyxWiz Hub
    """

    @staticmethod
    def UploadMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.ModelService/UploadMetadata',
            deployment__pb2.UploadModelMetadataRequest.SerializeToString,
            deployment__pb2.UploadModelMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cyxwiz.protocol.ModelService/UploadModel',
            deployment__pb2.ModelChunk.SerializeToString,
            deployment__pb2.SimpleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.ModelService/DownloadMetadata',
            deployment__pb2.DownloadModelMetadataRequest.SerializeToString,
            deployment__pb2.DownloadModelMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cyxwiz.protocol.ModelService/DownloadModel',
            deployment__pb2.DownloadModelMetadataRequest.SerializeToString,
            deployment__pb2.ModelChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.ModelService/ListModels',
            deployment__pb2.ListModelsRequest.SerializeToString,
            deployment__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.ModelService/DeleteModel',
            deployment__pb2.DeleteModelRequest.SerializeToString,
            deployment__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
