# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import execution_pb2 as execution__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobExecutionServiceStub(object):
    """Service running on Server Node (port 50052) for P2P communication with Engine
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectToNode = channel.unary_unary(
                '/cyxwiz.protocol.JobExecutionService/ConnectToNode',
                request_serializer=execution__pb2.ConnectRequest.SerializeToString,
                response_deserializer=execution__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.SendJob = channel.unary_unary(
                '/cyxwiz.protocol.JobExecutionService/SendJob',
                request_serializer=execution__pb2.SendJobRequest.SerializeToString,
                response_deserializer=execution__pb2.SendJobResponse.FromString,
                _registered_method=True)
        self.StreamTrainingMetrics = channel.stream_stream(
                '/cyxwiz.protocol.JobExecutionService/StreamTrainingMetrics',
                request_serializer=execution__pb2.TrainingCommand.SerializeToString,
                response_deserializer=execution__pb2.TrainingUpdate.FromString,
                _registered_method=True)
        self.DownloadWeights = channel.unary_stream(
                '/cyxwiz.protocol.JobExecutionService/DownloadWeights',
                request_serializer=execution__pb2.DownloadRequest.SerializeToString,
                response_deserializer=execution__pb2.WeightsChunk.FromString,
                _registered_method=True)


class JobExecutionServiceServicer(object):
    """Service running on Server Node (port 50052) for P2P communication with Engine
    """

    def ConnectToNode(self, request, context):
        """Engine establishes connection with auth token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendJob(self, request, context):
        """Engine sends job details and dataset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrainingMetrics(self, request_iterator, context):
        """Bidirectional streaming for real-time training updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadWeights(self, request, context):
        """Engine downloads final model weights
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectToNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectToNode,
                    request_deserializer=execution__pb2.ConnectRequest.FromString,
                    response_serializer=execution__pb2.ConnectResponse.SerializeToString,
            ),
            'SendJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SendJob,
                    request_deserializer=execution__pb2.SendJobRequest.FromString,
                    response_serializer=execution__pb2.SendJobResponse.SerializeToString,
            ),
            'StreamTrainingMetrics': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTrainingMetrics,
                    request_deserializer=execution__pb2.TrainingCommand.FromString,
                    response_serializer=execution__pb2.TrainingUpdate.SerializeToString,
            ),
            'DownloadWeights': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadWeights,
                    request_deserializer=execution__pb2.DownloadRequest.FromString,
                    response_serializer=execution__pb2.WeightsChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyxwiz.protocol.JobExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyxwiz.protocol.JobExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobExecutionService(object):
    """Service running on Server Node (port 50052) for P2P communication with Engine
    """

    @staticmethod
    def ConnectToNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.JobExecutionService/ConnectToNode',
            execution__pb2.ConnectRequest.SerializeToString,
            execution__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.JobExecutionService/SendJob',
            execution__pb2.SendJobRequest.SerializeToString,
            execution__pb2.SendJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTrainingMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cyxwiz.protocol.JobExecutionService/StreamTrainingMetrics',
            execution__pb2.TrainingCommand.SerializeToString,
            execution__pb2.TrainingUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cyxwiz.protocol.JobExecutionService/DownloadWeights',
            execution__pb2.DownloadRequest.SerializeToString,
            execution__pb2.WeightsChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
