# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import job_pb2 as job__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in job_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobServiceStub(object):
    """Job Service - Client to Central Server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/cyxwiz.protocol.JobService/SubmitJob',
                request_serializer=job__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=job__pb2.SubmitJobResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/cyxwiz.protocol.JobService/GetJobStatus',
                request_serializer=job__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=job__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/cyxwiz.protocol.JobService/CancelJob',
                request_serializer=job__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=job__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.StreamJobUpdates = channel.unary_stream(
                '/cyxwiz.protocol.JobService/StreamJobUpdates',
                request_serializer=job__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=job__pb2.JobUpdateStream.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/cyxwiz.protocol.JobService/ListJobs',
                request_serializer=job__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=job__pb2.ListJobsResponse.FromString,
                _registered_method=True)


class JobServiceServicer(object):
    """Job Service - Client to Central Server
    """

    def SubmitJob(self, request, context):
        """Submit a new job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Query job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancel a job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobUpdates(self, request, context):
        """Stream real-time job updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """List user's jobs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=job__pb2.SubmitJobRequest.FromString,
                    response_serializer=job__pb2.SubmitJobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=job__pb2.GetJobStatusRequest.FromString,
                    response_serializer=job__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=job__pb2.CancelJobRequest.FromString,
                    response_serializer=job__pb2.CancelJobResponse.SerializeToString,
            ),
            'StreamJobUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobUpdates,
                    request_deserializer=job__pb2.GetJobStatusRequest.FromString,
                    response_serializer=job__pb2.JobUpdateStream.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=job__pb2.ListJobsRequest.FromString,
                    response_serializer=job__pb2.ListJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyxwiz.protocol.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyxwiz.protocol.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Job Service - Client to Central Server
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.JobService/SubmitJob',
            job__pb2.SubmitJobRequest.SerializeToString,
            job__pb2.SubmitJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.JobService/GetJobStatus',
            job__pb2.GetJobStatusRequest.SerializeToString,
            job__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.JobService/CancelJob',
            job__pb2.CancelJobRequest.SerializeToString,
            job__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cyxwiz.protocol.JobService/StreamJobUpdates',
            job__pb2.GetJobStatusRequest.SerializeToString,
            job__pb2.JobUpdateStream.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.JobService/ListJobs',
            job__pb2.ListJobsRequest.SerializeToString,
            job__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
