# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import node_pb2 as node__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """Node Service - Central Server to Server Node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/cyxwiz.protocol.NodeService/RegisterNode',
                request_serializer=node__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=node__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/cyxwiz.protocol.NodeService/Heartbeat',
                request_serializer=node__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=node__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.AssignJob = channel.unary_unary(
                '/cyxwiz.protocol.NodeService/AssignJob',
                request_serializer=node__pb2.AssignJobRequest.SerializeToString,
                response_deserializer=node__pb2.AssignJobResponse.FromString,
                _registered_method=True)
        self.ReportProgress = channel.unary_unary(
                '/cyxwiz.protocol.NodeService/ReportProgress',
                request_serializer=node__pb2.ReportProgressRequest.SerializeToString,
                response_deserializer=node__pb2.ReportProgressResponse.FromString,
                _registered_method=True)
        self.ReportCompletion = channel.unary_unary(
                '/cyxwiz.protocol.NodeService/ReportCompletion',
                request_serializer=node__pb2.ReportCompletionRequest.SerializeToString,
                response_deserializer=node__pb2.ReportCompletionResponse.FromString,
                _registered_method=True)
        self.GetNodeMetrics = channel.unary_unary(
                '/cyxwiz.protocol.NodeService/GetNodeMetrics',
                request_serializer=node__pb2.GetNodeMetricsRequest.SerializeToString,
                response_deserializer=node__pb2.GetNodeMetricsResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Node Service - Central Server to Server Node
    """

    def RegisterNode(self, request, context):
        """Node registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Keep-alive heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignJob(self, request, context):
        """Assign job to node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportProgress(self, request, context):
        """Report job progress
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCompletion(self, request, context):
        """Report job completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeMetrics(self, request, context):
        """Get node metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=node__pb2.RegisterNodeRequest.FromString,
                    response_serializer=node__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=node__pb2.HeartbeatRequest.FromString,
                    response_serializer=node__pb2.HeartbeatResponse.SerializeToString,
            ),
            'AssignJob': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignJob,
                    request_deserializer=node__pb2.AssignJobRequest.FromString,
                    response_serializer=node__pb2.AssignJobResponse.SerializeToString,
            ),
            'ReportProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=node__pb2.ReportProgressRequest.FromString,
                    response_serializer=node__pb2.ReportProgressResponse.SerializeToString,
            ),
            'ReportCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCompletion,
                    request_deserializer=node__pb2.ReportCompletionRequest.FromString,
                    response_serializer=node__pb2.ReportCompletionResponse.SerializeToString,
            ),
            'GetNodeMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeMetrics,
                    request_deserializer=node__pb2.GetNodeMetricsRequest.FromString,
                    response_serializer=node__pb2.GetNodeMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyxwiz.protocol.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyxwiz.protocol.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Node Service - Central Server to Server Node
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.NodeService/RegisterNode',
            node__pb2.RegisterNodeRequest.SerializeToString,
            node__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.NodeService/Heartbeat',
            node__pb2.HeartbeatRequest.SerializeToString,
            node__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.NodeService/AssignJob',
            node__pb2.AssignJobRequest.SerializeToString,
            node__pb2.AssignJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.NodeService/ReportProgress',
            node__pb2.ReportProgressRequest.SerializeToString,
            node__pb2.ReportProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.NodeService/ReportCompletion',
            node__pb2.ReportCompletionRequest.SerializeToString,
            node__pb2.ReportCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.NodeService/GetNodeMetrics',
            node__pb2.GetNodeMetricsRequest.SerializeToString,
            node__pb2.GetNodeMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NodeDiscoveryServiceStub(object):
    """Node Discovery Service - For finding available nodes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindNodes = channel.unary_unary(
                '/cyxwiz.protocol.NodeDiscoveryService/FindNodes',
                request_serializer=node__pb2.FindNodesRequest.SerializeToString,
                response_deserializer=node__pb2.FindNodesResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/cyxwiz.protocol.NodeDiscoveryService/ListNodes',
                request_serializer=node__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=node__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.GetNodeInfo = channel.unary_unary(
                '/cyxwiz.protocol.NodeDiscoveryService/GetNodeInfo',
                request_serializer=node__pb2.GetNodeInfoRequest.SerializeToString,
                response_deserializer=node__pb2.GetNodeInfoResponse.FromString,
                _registered_method=True)


class NodeDiscoveryServiceServicer(object):
    """Node Discovery Service - For finding available nodes
    """

    def FindNodes(self, request, context):
        """Find available nodes matching requirements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """List all nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeInfo(self, request, context):
        """Get specific node info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeDiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.FindNodes,
                    request_deserializer=node__pb2.FindNodesRequest.FromString,
                    response_serializer=node__pb2.FindNodesResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=node__pb2.ListNodesRequest.FromString,
                    response_serializer=node__pb2.ListNodesResponse.SerializeToString,
            ),
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=node__pb2.GetNodeInfoRequest.FromString,
                    response_serializer=node__pb2.GetNodeInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyxwiz.protocol.NodeDiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyxwiz.protocol.NodeDiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeDiscoveryService(object):
    """Node Discovery Service - For finding available nodes
    """

    @staticmethod
    def FindNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.NodeDiscoveryService/FindNodes',
            node__pb2.FindNodesRequest.SerializeToString,
            node__pb2.FindNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.NodeDiscoveryService/ListNodes',
            node__pb2.ListNodesRequest.SerializeToString,
            node__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.NodeDiscoveryService/GetNodeInfo',
            node__pb2.GetNodeInfoRequest.SerializeToString,
            node__pb2.GetNodeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class JobStatusServiceStub(object):
    """Job Status Service - Implemented by Central Server, called by Server Nodes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateJobStatus = channel.unary_unary(
                '/cyxwiz.protocol.JobStatusService/UpdateJobStatus',
                request_serializer=node__pb2.UpdateJobStatusRequest.SerializeToString,
                response_deserializer=node__pb2.UpdateJobStatusResponse.FromString,
                _registered_method=True)
        self.ReportJobResult = channel.unary_unary(
                '/cyxwiz.protocol.JobStatusService/ReportJobResult',
                request_serializer=node__pb2.ReportJobResultRequest.SerializeToString,
                response_deserializer=node__pb2.ReportJobResultResponse.FromString,
                _registered_method=True)


class JobStatusServiceServicer(object):
    """Job Status Service - Implemented by Central Server, called by Server Nodes
    """

    def UpdateJobStatus(self, request, context):
        """Update job progress during execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportJobResult(self, request, context):
        """Report final job result (completion or failure)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobStatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJobStatus,
                    request_deserializer=node__pb2.UpdateJobStatusRequest.FromString,
                    response_serializer=node__pb2.UpdateJobStatusResponse.SerializeToString,
            ),
            'ReportJobResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportJobResult,
                    request_deserializer=node__pb2.ReportJobResultRequest.FromString,
                    response_serializer=node__pb2.ReportJobResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyxwiz.protocol.JobStatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cyxwiz.protocol.JobStatusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobStatusService(object):
    """Job Status Service - Implemented by Central Server, called by Server Nodes
    """

    @staticmethod
    def UpdateJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.JobStatusService/UpdateJobStatus',
            node__pb2.UpdateJobStatusRequest.SerializeToString,
            node__pb2.UpdateJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportJobResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cyxwiz.protocol.JobStatusService/ReportJobResult',
            node__pb2.ReportJobResultRequest.SerializeToString,
            node__pb2.ReportJobResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
