#include "node_type_import_registry.h"

#include <array>

namespace gui {
namespace {

constexpr std::array<NodeTypeImportName, 199> kNodeTypeImportNames = {{
        {"Dense", NodeType::Dense},
        {"Conv1D", NodeType::Conv1D},
        {"Conv2D", NodeType::Conv2D},
        {"Conv3D", NodeType::Conv3D},
        {"DepthwiseConv2D", NodeType::DepthwiseConv2D},
        {"MaxPool2D", NodeType::MaxPool2D},
        {"AvgPool2D", NodeType::AvgPool2D},
        {"GlobalMaxPool", NodeType::GlobalMaxPool},
        {"GlobalAvgPool", NodeType::GlobalAvgPool},
        {"AdaptiveAvgPool", NodeType::AdaptiveAvgPool},
        {"BatchNorm", NodeType::BatchNorm},
        {"LayerNorm", NodeType::LayerNorm},
        {"GroupNorm", NodeType::GroupNorm},
        {"InstanceNorm", NodeType::InstanceNorm},
        {"Dropout", NodeType::Dropout},
        {"Flatten", NodeType::Flatten},
        {"RNN", NodeType::RNN},
        {"LSTM", NodeType::LSTM},
        {"GRU", NodeType::GRU},
        {"Bidirectional", NodeType::Bidirectional},
        {"TimeDistributed", NodeType::TimeDistributed},
        {"Embedding", NodeType::Embedding},
        {"MultiHeadAttention", NodeType::MultiHeadAttention},
        {"SelfAttention", NodeType::SelfAttention},
        {"CrossAttention", NodeType::CrossAttention},
        {"LinearAttention", NodeType::LinearAttention},
        {"TransformerEncoder", NodeType::TransformerEncoder},
        {"TransformerDecoder", NodeType::TransformerDecoder},
        {"PositionalEncoding", NodeType::PositionalEncoding},
        {"ReLU", NodeType::ReLU},
        {"LeakyReLU", NodeType::LeakyReLU},
        {"PReLU", NodeType::PReLU},
        {"ELU", NodeType::ELU},
        {"SELU", NodeType::SELU},
        {"GELU", NodeType::GELU},
        {"Swish", NodeType::Swish},
        {"Mish", NodeType::Mish},
        {"Sigmoid", NodeType::Sigmoid},
        {"Tanh", NodeType::Tanh},
        {"Softmax", NodeType::Softmax},
        {"Reshape", NodeType::Reshape},
        {"Permute", NodeType::Permute},
        {"Squeeze", NodeType::Squeeze},
        {"Unsqueeze", NodeType::Unsqueeze},
        {"View", NodeType::View},
        {"Split", NodeType::Split},
        {"Concatenate", NodeType::Concatenate},
        {"Add", NodeType::Add},
        {"Multiply", NodeType::Multiply},
        {"Average", NodeType::Average},
        {"TensorSum", NodeType::TensorSum},
        {"TensorMean", NodeType::TensorMean},
        {"TensorMax", NodeType::TensorMax},
        {"TensorMin", NodeType::TensorMin},
        {"TensorProd", NodeType::TensorProd},
        {"TensorVar", NodeType::TensorVar},
        {"TensorStd", NodeType::TensorStd},
        {"TensorBroadcastTo", NodeType::TensorBroadcastTo},
        {"TensorExpand", NodeType::TensorExpand},
        {"TensorIndexSelect", NodeType::TensorIndexSelect},
        {"TensorPow", NodeType::TensorPow},
        {"TensorSqrt", NodeType::TensorSqrt},
        {"TensorExp", NodeType::TensorExp},
        {"TensorLog", NodeType::TensorLog},
        {"TensorAbs", NodeType::TensorAbs},
        {"TensorSign", NodeType::TensorSign},
        {"TensorClip", NodeType::TensorClip},
        {"TensorDot", NodeType::TensorDot},
        {"TensorBatchMatMul", NodeType::TensorBatchMatMul},
        {"TensorCompare", NodeType::TensorCompare},
        {"TensorLogicalMask", NodeType::TensorLogicalMask},
        {"Output", NodeType::Output},
        {"MSELoss", NodeType::MSELoss},
        {"CrossEntropyLoss", NodeType::CrossEntropyLoss},
        {"BCELoss", NodeType::BCELoss},
        {"BCEWithLogits", NodeType::BCEWithLogits},
        {"L1Loss", NodeType::L1Loss},
        {"SmoothL1Loss", NodeType::SmoothL1Loss},
        {"HuberLoss", NodeType::HuberLoss},
        {"NLLLoss", NodeType::NLLLoss},
        {"SoftDiceLoss", NodeType::SoftDiceLoss},
        {"TverskyLoss", NodeType::TverskyLoss},
        {"JaccardLoss", NodeType::JaccardLoss},
        {"ClassificationMetricsNode", NodeType::ClassificationMetricsNode},
        {"SGD", NodeType::SGD},
        {"Adam", NodeType::Adam},
        {"AdamW", NodeType::AdamW},
        {"RMSprop", NodeType::RMSprop},
        {"Adagrad", NodeType::Adagrad},
        {"NAdam", NodeType::NAdam},
        {"StepLR", NodeType::StepLR},
        {"CosineAnnealing", NodeType::CosineAnnealing},
        {"ReduceOnPlateau", NodeType::ReduceOnPlateau},
        {"ExponentialLR", NodeType::ExponentialLR},
        {"WarmupScheduler", NodeType::WarmupScheduler},
        {"L1Regularization", NodeType::L1Regularization},
        {"L2Regularization", NodeType::L2Regularization},
        {"ElasticNet", NodeType::ElasticNet},
        {"Lambda", NodeType::Lambda},
        {"Identity", NodeType::Identity},
        {"Constant", NodeType::Constant},
        {"Parameter", NodeType::Parameter},
        {"DataInput", NodeType::DataInput},
        {"DataOutput", NodeType::DataOutput},
        {"DatasetInput", NodeType::DatasetInput, true},
        {"DataLoader", NodeType::DataLoader},
        {"Augmentation", NodeType::Augmentation},
        {"DataSplit", NodeType::DataSplit},
        {"TensorReshape", NodeType::TensorReshape},
        {"Normalize", NodeType::Normalize},
        {"OneHotEncode", NodeType::OneHotEncode},
        {"TextTokenizer", NodeType::TextTokenizer},
        {"TextVocabulary", NodeType::TextVocabulary},
        {"TextPadding", NodeType::TextPadding},
        {"NERSequenceBuilder", NodeType::NERSequenceBuilder},
        {"TokenVocabulary", NodeType::TokenVocabulary},
        {"POSVocabulary", NodeType::POSVocabulary},
        {"NERTagVocabulary", NodeType::NERTagVocabulary},
        {"SequenceTagOutput", NodeType::SequenceTagOutput},
        {"PairDatasetBuilder", NodeType::PairDatasetBuilder},
        {"TripletDatasetBuilder", NodeType::TripletDatasetBuilder},
        {"SharedEncoder", NodeType::SharedEncoder},
        {"SiameseBranch", NodeType::SiameseBranch},
        {"ContrastiveLoss", NodeType::ContrastiveLoss},
        {"CosineEmbeddingLoss", NodeType::CosineEmbeddingLoss},
        {"TripletLoss", NodeType::TripletLoss},
        {"PairMetrics", NodeType::PairMetrics},
        {"RetrievalMetrics", NodeType::RetrievalMetrics},
        {"EmbeddingOutput", NodeType::EmbeddingOutput},
        {"PairScoreOutput", NodeType::PairScoreOutput},
        {"TimeSeriesWindow", NodeType::TimeSeriesWindow},
        {"TimeSeriesFeatures", NodeType::TimeSeriesFeatures},
        {"TimeSeriesSplit", NodeType::TimeSeriesSplit},
        {"TimeSeriesCSV", NodeType::TimeSeriesCSV, true},
        {"Spectrogram", NodeType::Spectrogram},
        {"MelSpectrogram", NodeType::MelSpectrogram},
        {"MFCC", NodeType::MFCC},
        {"AudioAugmentation", NodeType::AudioAugmentation},
        {"LogTransform", NodeType::LogTransform},
        {"Differencing", NodeType::Differencing},
        {"TimeSeriesDecomposition", NodeType::TimeSeriesDecomposition},
        {"ACFNode", NodeType::ACFNode},
        {"PACFNode", NodeType::PACFNode},
        {"StationarityTest", NodeType::StationarityTest},
        {"SeasonalityDetector", NodeType::SeasonalityDetector},
        {"ARIMAForecaster", NodeType::ARIMAForecaster},
        {"ExponentialSmoothing", NodeType::ExponentialSmoothing},
        {"DeployToNodeEditorNode", NodeType::DeployToNodeEditorNode},
        {"Input", NodeType::DatasetInput, true},
        {"GlobalAvgPool2D", NodeType::GlobalAvgPool},
        {"BatchNorm2D", NodeType::BatchNorm},
        {"Concat", NodeType::Concatenate},
        {"CrossEntropy", NodeType::CrossEntropyLoss},
        {"FocalLoss", NodeType::FocalLoss},
        {"Focal", NodeType::FocalLoss},
        {"SoftDice", NodeType::SoftDiceLoss},
        {"DiceLoss", NodeType::SoftDiceLoss},
        {"Tversky", NodeType::TverskyLoss},
        {"Jaccard", NodeType::JaccardLoss},
        {"IoULoss", NodeType::JaccardLoss},
        {"IoU", NodeType::JaccardLoss},
        {"StandardScaler", NodeType::StandardScaler},
        {"MinMaxScaler", NodeType::MinMaxScaler},
        {"RobustScaler", NodeType::RobustScaler},
        {"LabelEncoder", NodeType::LabelEncoder},
        {"OrdinalEncoder", NodeType::OrdinalEncoder},
        {"TargetEncoder", NodeType::TargetEncoder},
        {"BinningNode", NodeType::BinningNode},
        {"PolynomialFeaturesNode", NodeType::PolynomialFeaturesNode},
        {"OutlierDetector", NodeType::OutlierDetector},
        {"PCANode", NodeType::PCANode},
        {"KMeansCluster", NodeType::KMeansCluster},
        {"DBSCANCluster", NodeType::DBSCANCluster},
        {"HierarchicalCluster", NodeType::HierarchicalCluster},
        {"GMMCluster", NodeType::GMMCluster},
        {"LinearRegressionNode", NodeType::LinearRegressionNode},
        {"PolynomialRegressionNode", NodeType::PolynomialRegressionNode},
        {"DecisionTreeClassifier", NodeType::DecisionTreeClassifier},
        {"RandomForestClassifier", NodeType::RandomForestClassifier},
        {"GradientBoostingClassifier", NodeType::GradientBoostingClassifier},
        {"TreeModelPredictor", NodeType::TreeModelPredictor},
        {"TextCleanNode", NodeType::TextCleanNode},
        {"TFIDFVectorizer", NodeType::TFIDFVectorizer},
        {"CountVectorizer", NodeType::CountVectorizer},
        {"SentimentAnalyzer", NodeType::SentimentAnalyzer},
        {"TimeSeriesLag", NodeType::TimeSeriesLag},
        {"SeasonalNaive", NodeType::SeasonalNaive},
        {"Resize", NodeType::Resize},
        {"CenterCrop", NodeType::CenterCrop},
        {"RandomCrop", NodeType::RandomCrop},
        {"HorizontalFlip", NodeType::HorizontalFlip},
        {"VerticalFlip", NodeType::VerticalFlip},
        {"ImageRotate", NodeType::ImageRotate},
        {"ColorJitter", NodeType::ColorJitter},
        {"ImageGaussianBlur", NodeType::ImageGaussianBlur},
        {"Grayscale", NodeType::Grayscale},
        {"FFTNode", NodeType::FFTNode},
        {"FilterDesigner", NodeType::FilterDesigner},
        {"Convolution1D", NodeType::Convolution1D},
}};

} // namespace

std::span<const NodeTypeImportName> GetNodeTypeImportNames() {
    return kNodeTypeImportNames;
}

std::optional<NodeType> ResolveNodeTypeImportName(std::string_view name) {
    for (const auto& entry : kNodeTypeImportNames) {
        if (entry.name == name) return entry.node_type;
    }
    return std::nullopt;
}

} // namespace gui
