#pragma once

// DataLoader — polymorphic entry point for per-category data loading.
//
// Commit 1 (this commit) lands the Apply-time async surface and a single
// concrete loader (TabularLoader). DataInputDialog's tabular branch now
// dispatches through this interface instead of an inline ~200-line block.
// The remaining four branches (Text / Image / Audio / Video) stay inline
// and will migrate in commits 2-4.
//
// Why a shared AsyncLoadState in this header: the dialog holds the
// shared_ptr as a member, every category-specific branch writes into it
// from its worker, and PollAsyncLoadResult on the UI thread drains it.
// Before this refactor the struct was a private nested type in
// DataInputDialog — fine when only the dialog produced into it, but the
// loader module is now a producer too. Hoisting it out of the dialog
// keeps the struct small and ownership obvious (shared_ptr owns, worker
// writes, PollAsyncLoadResult reads).

#include <atomic>
#include <cstdint>
#include <functional>
#include <memory>
#include <string>
#include <vector>

// Forward-declared MLNode: loader RestoreFromRegistry needs read-only
// access to node->parameters to pull per-node hints (e.g. image
// target_width / target_height / rgb overrides) without dragging the
// full node_editor.h into this header.
namespace gui { struct MLNode; }

// Forward declarations for LaunchTraining. The full types come from
// core/graph_compiler.h + gui/panels/training_plot_panel.h; forward-
// declaring them keeps this header from pulling in the whole training
// toolchain for callers that only use the Apply-time surface.
namespace cyxwiz {
    struct TrainingConfiguration;
    class TrainingPlotPanel;
}

namespace cyxwiz::loaders {

// Category of file/dataset this loader handles. Canonical definition
// lives here; DataInputDialog::FileCategory is a type alias pointing
// back so the dialog's many existing `FileCategory::Tabular` usages
// continue to compile unchanged.
enum class FileCategory {
    Tabular,
    Image,
    Audio,
    Video,
    Text,
    TimeSeries,
};

// Worker-to-UI handoff for a single async load. The worker fills every
// field other than `done`, then calls `done.store(true)` LAST as a
// publish barrier. `PollAsyncLoadResult` on the UI thread reads fields
// only after seeing `done == true`, guaranteeing it sees a fully
// initialized state.
//
// Owned by shared_ptr so the worker keeps the struct alive even if the
// dialog is destroyed mid-load.
struct AsyncLoadState {
    std::atomic<bool> done{false};   // publish barrier — set LAST in every worker
    bool success = false;            // valid once done == true
    int backend = 0;                 // BackendTag of the producer (see DataLoader::BackendTag)
    int64_t rows = 0;
    int64_t cols = 0;
    size_t bytes = 0;
    std::string message;             // user-facing status line (success or error)
    std::string dataset_name;        // registry key the worker registered under
    std::string source_path;         // file_path or folder_path that was loaded
    int num_classes = 0;             // set by image/audio/text loaders
    int vocab_size = 0;              // set by text loader
};

// Snapshot of dialog state the loader needs at Apply time. Copied by
// value on the UI thread; the loader's LaunchAsyncLoad then captures
// fields by value into its worker lambda so the dialog can be closed
// mid-load without racing.
struct ApplyContext {
    // Common to every category
    std::string dataset_name;            // already generated by the dialog
    std::string source_path;             // file_path for Tabular, folder_path for Image/Audio
    std::string previous_dataset_name;   // prior Apply's name, if any (for cleanup)

    // Tabular-specific ------------------------------------------------
    // detected_file_type is the stringified enum index — "auto", "csv",
    // "tsv", "json", "parquet", "excel", "hdf5", "feather", "arrow",
    // "txt", "arff". LoadTabularCSV handles csv/tsv/txt/arff; the
    // others each have a dedicated LoadXToArrow call.
    std::string detected_file_type;
    bool has_header = true;
    char delimiter = ',';
    int skip_rows = 0;
    int64_t max_rows = 0;                 // 0 means "all rows"
    bool force_disk_backed = false;
    bool json_lines = false;
    int excel_sheet_idx = 0;

    // Text-specific (commit 2) -------------------------------------
    // text_has_labels is `true` when the corpus is class-subdir layout
    // (folder/<class>/*.txt) or when the user picked a label column
    // for a single-file corpus. text_tokenizer_type is the raw enum
    // index from the dialog: 0=Whitespace, 1=Word, 2=Character.
    std::string text_column;
    std::string text_label_column;
    bool text_has_labels = false;
    int text_tokenizer_type = 1;
    int text_max_length = 512;
    bool text_lowercase = true;
    int text_min_freq = 1;
    int text_max_vocab_size = -1;

    // Image-specific (commit 3) ------------------------------------
    // image_layout mirrors DataInputDialog::ImageLayout as an int so
    // the loader doesn't depend on the dialog's private enum:
    //   0 = ClassSubdirs (folder/<class>/*.jpg — ImageNet style)
    //   1 = FlatWithCSV  (folder/*.jpg + labels_csv mapping name→label)
    // image_{w,h,c} are only used to estimate AsyncLoadState::bytes
    // for the Memory tab; pixels are loaded lazily at training time.
    std::string image_labels_csv;
    int image_layout = 0;
    int image_width = 224;
    int image_height = 224;
    int image_channels = 3;

    // Audio-specific (commit 4) ------------------------------------
    // audio_labeled_subdirs == true  → folder/<class>/*.wav layout.
    // audio_labeled_subdirs == false → flat folder + audio_labels_csv
    //   with audio_filename_col / audio_label_col (empty = auto-detect
    //   by header name). Feature-extraction knobs (sr, max_duration,
    //   n_fft, hop_length, n_mels, n_mfcc) are defaults pushed into
    //   AudioDatasetEntry so training-time GetItem produces tensors
    //   shaped the same way they were probed here.
    std::string audio_labels_csv;
    std::string audio_filename_col;
    std::string audio_label_col;
    bool audio_labeled_subdirs = true;
    int audio_target_sr = 16000;
    float audio_max_duration = 5.0f;
    int audio_n_fft = 512;
    int audio_hop_length = 256;
    int audio_n_mels = 128;
    int audio_n_mfcc = 13;
    int audio_feature_type = 1;  // 1 = MelSpectrogram (default)
};

// Populated by DataLoader::RestoreFromRegistry from registry metadata
// when a dialog reopens on an already-loaded dataset. The dialog splats
// these fields into its loaded_* members so the Memory tab + compile
// gate see the same state they did right after Apply finished.
struct RestoreState {
    bool found = false;              // false → dataset not in registry
    int64_t rows = 0;
    int64_t cols = 0;
    size_t bytes = 0;
    int backend = 0;                 // BackendTag that was used (1..5)
    bool memory_is_estimate = false; // true for image/audio/text (lazy)
    std::string status_message;      // user-facing line for the Memory tab
};

// Returned by DataLoader::DescribeCompletedLoad once PollAsyncLoadResult
// drains an AsyncLoadState. The dialog uses these strings to format
// node->description + apply_status_message_. Keeps per-category format
// rules (images → "N images, K classes", tabular → "N rows, M cols")
// in the owning loader instead of an if/else-if chain in the dialog.
struct CompletedLoadDescription {
    std::string node_description_suffix;  // appended after "<filename>\n"
    std::string default_status_message;   // fallback when state->message is empty
    bool memory_is_estimate = false;      // true for lazy-loaded backends
};

// Abstract base. The interface grows commit-by-commit as each feature
// migrates into the loader module (Apply/async → restore → memory tab
// → training dispatch → compile gate).
class DataLoader {
public:
    virtual ~DataLoader() = default;

    // === Identity ===
    virtual FileCategory Category() const = 0;
    virtual const char* CategoryName() const = 0;

    // Numeric tag written into AsyncLoadState::backend and (later) node
    // params. 1 = Arrow in-memory (tabular), 2 = Parquet disk-backed
    // (tabular — picked at load time, overrides the primary tag),
    // 3 = image folder, 4 = audio folder, 5 = text in-memory.
    virtual int BackendTag() const = 0;

    // True when the loader's backend is lazy — AsyncLoadState::bytes
    // is a "fully cached" estimate, not actual RAM use. Text / Image /
    // Audio are lazy; Tabular (Arrow in-memory and Parquet disk-backed)
    // is not — Arrow has real bytes, Parquet is disk-cached. The dialog
    // uses this to label the Memory tab honestly and to drive
    // loaded_memory_is_estimate_.
    virtual bool IsLazyLoaded() const = 0;

    // === Apply-time async ===
    // Fast UI-thread precheck. Populate `err` with a user-facing message
    // and return false to abort the load before spinning up a worker.
    virtual bool ValidateApplyContext(const ApplyContext& ctx,
                                      std::string& err) const = 0;

    // Queue the load onto AsyncTaskManager. Returns the task id (or 0
    // on immediate failure). The worker MUST set `state->done.store(true)`
    // LAST so the UI thread only reads a fully initialized state.
    virtual uint64_t LaunchAsyncLoad(const ApplyContext& ctx,
                                     std::shared_ptr<AsyncLoadState> state) = 0;

    // === Registry coordination ===
    virtual bool IsRegistered(const std::string& name) const = 0;
    virtual void Unregister(const std::string& name) = 0;

    // === Restore on dialog reopen (commit 5) ===
    // Populates `out` from the registry entry for `name`. Returns false
    // if the dataset isn't in the registry (dialog treats this as
    // "dataset was closed or cleared — show Not Loaded"). The `node`
    // argument gives read-only access to per-node params like
    // target_width/target_height/rgb for image memory estimates.
    virtual bool RestoreFromRegistry(const std::string& name,
                                     const gui::MLNode& node,
                                     RestoreState& out) const = 0;

    // === Async-completion description (commit 5) ===
    // Formats the strings the dialog splats into node->description +
    // apply_status_message_ after PollAsyncLoadResult drains a
    // successful AsyncLoadState.
    virtual CompletedLoadDescription DescribeCompletedLoad(
        const AsyncLoadState& state) const = 0;

    // === Training dispatch (commit 6) ===
    // Look up the registry entry for `dataset_name` and hand it to the
    // right TrainingManager::StartTraining* method. Returns false if
    // the registry entry is missing (registered but not retrievable,
    // which would be a TOCTOU bug) or if TrainingManager declined to
    // start (another session already running).
    //
    // Callers (MainWindow::StartTrainingFromGraph) used to fan out via
    // a 5-way if/else-if on dataset type and a per-branch
    // TrainingManager::StartTrainingX call. This method collapses that
    // into a virtual dispatch — each loader owns the knowledge of
    // which registry entry to fetch and which TrainingManager method
    // to call.
    virtual bool LaunchTraining(
        TrainingConfiguration config,
        const std::string& dataset_name,
        const std::string& label_column,
        int epochs,
        int batch_size,
        TrainingPlotPanel* plot_panel,
        std::function<void(bool)> node_editor_callback) = 0;
};

// === Factory ===
//
// TabularLoader (also serving the TimeSeries category — same load path,
// different params) is registered first; TextLoader, ImageLoader, and
// AudioLoader follow. Video is deliberately unregistered — the guard at
// the top of DataInputDialog::Apply fails video loads loudly before
// reaching the dispatch.
DataLoader* GetByCategory(FileCategory cat);

// Resolves a registered dataset name back to its loader. Uses
// DataRegistry::ResolveCategory (the routing sidecar) for O(1) lookup;
// falls back to a linear IsRegistered walk for legacy names that
// predate the sidecar. Returns nullptr if the dataset isn't registered.
DataLoader* GetByRegisteredDataset(const std::string& name);

// Find the loader whose BackendTag equals `backend`. Tabular covers
// both backend 1 (Arrow in-memory) and backend 2 (Parquet disk-backed)
// — its BackendTag() returns 1, but this helper also maps 2 → Tabular
// so the Memory tab / PollAsyncLoadResult can reach the owning loader
// from a stored backend int. Returns nullptr for unknown backends.
DataLoader* GetByBackendTag(int backend);

// All registered loaders, in registration order.
const std::vector<DataLoader*>& All();

}  // namespace cyxwiz::loaders
