"""Generate cyxwiz-engine/src/core/plot/world_countries_110m.inc from Natural Earth.

Source: Natural Earth 1:110m Admin 0 - Countries (public domain),
https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson

Usage: python gen_world_map.py ne_110m_admin_0_countries.geojson
Coordinates are stored in hundredths of a degree (int16), outer rings only
(the one hole at this scale, Lesotho in South Africa, is its own country).
"""
import json
import os
import sys

src = sys.argv[1]
out = os.path.join(os.path.dirname(__file__), '..', 'src', 'core', 'plot', 'world_countries_110m.inc')
gj = json.load(open(src, encoding='utf-8'))


def c(s):
    return '"' + str(s or '').replace('\\', '\\\\').replace('"', '\\"') + '"'


countries, rings, coords = [], [], []
for f in sorted(gj['features'], key=lambda f: f['properties']['NAME']):
    p = f['properties']
    g = f['geometry']
    polys = [g['coordinates']] if g['type'] == 'Polygon' else g['coordinates']
    first = len(rings)
    for poly in polys:
        ring = poly[0]
        if ring[0] == ring[-1]:
            ring = ring[:-1]
        rings.append((len(coords) // 2, len(ring)))
        for lon, lat in ring:
            coords += [round(lon * 100), round(lat * 100)]
    iso3 = p['ISO_A3_EH'] if p['ISO_A3_EH'] != '-99' else ''
    iso2 = p['ISO_A2_EH'] if p['ISO_A2_EH'] != '-99' else ''
    countries.append(f'    {{{c(p["NAME"])}, {c(p["NAME_LONG"])}, {c(p["ADMIN"])}, {c(p["FORMAL_EN"])}, {c(iso3)}, {c(iso2)}, '
                     f'{c(p["CONTINENT"])}, {first}, {len(rings) - first}}},')

lines = ['// Generated by cyxwiz-engine/tools/gen_world_map.py from Natural Earth 1:110m', '// Admin 0 - Countries (public domain). Do not edit.', '']
lines.append('const RawCountry kRawCountries[] = {')
lines += countries
lines.append('};')
lines.append('const RawRing kRawRings[] = {')
for i in range(0, len(rings), 8):
    lines.append('    ' + ' '.join(f'{{{a}, {b}}},' for a, b in rings[i:i + 8]))
lines.append('};')
lines.append('const short kRawCoords[] = {')
for i in range(0, len(coords), 16):
    lines.append('    ' + ' '.join(f'{v},' for v in coords[i:i + 16]))
lines.append('};')
open(out, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
print(len(countries), 'countries,', len(rings), 'rings,', len(coords) // 2, 'points ->', os.path.normpath(out))
