"""Writes src/core/plot/plot_scales.inc: the colour scales the plot colour picker offers
(TOFIX134 P4.4, board 16), 16 stops each, sampled from matplotlib's colormaps.

Run from cyxwiz-engine/:  python tools/gen_plot_scales.py
Needs matplotlib (3.10 was used).
"""
import os

import matplotlib

# id saved in plot specs, label shown, two-sided (centred on 0), matplotlib name
SCALES = [
    ('viridis', 'Viridis', False, 'viridis'),
    ('plasma', 'Plasma', False, 'plasma'),
    ('magma', 'Magma', False, 'magma'),
    ('cividis', 'Cividis', False, 'cividis'),
    ('turbo', 'Turbo', False, 'turbo'),
    ('greys', 'Greys', False, 'Greys_r'),
    ('coolwarm', 'Cool-warm', True, 'coolwarm'),
]


def main():
    out = [
        '// Generated by tools/gen_plot_scales.py from matplotlib %s colormaps (16 stops each).' % matplotlib.__version__,
        '// Viridis, Plasma, Magma, Cividis: CC0 (Smith, van der Walt, Nunez); Turbo: Apache-2.0 (Google LLC);',
        '// Greys and Cool-warm (Moreland): matplotlib (PSF-based licence). RGB 0..1, low to high.',
    ]
    for sid, label, two_sided, name in SCALES:
        cm = matplotlib.colormaps[name]
        stops = ', '.join('{%.4ff, %.4ff, %.4ff}' % cm(i / 15)[:3] for i in range(16))
        out.append('{"%s", "%s", %s, {{%s}}},' % (sid, label, 'true' if two_sided else 'false', stops))
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, '..', 'src', 'core', 'plot', 'plot_scales.inc')
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out) + '\n')
    print('wrote', os.path.normpath(path))


if __name__ == '__main__':
    main()
